"""Initial Trade Opportunity schema

Revision ID: 0e3cc6443aec
Revises:
Create Date: 2026-09-01 12:32:48.635140

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0e3cc6443aec"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE SCHEMA IF NOT EXISTS "trade_opportunity"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("iso2", sa.CHAR(length=2), nullable=False),
        sa.Column("iso3", sa.CHAR(length=3), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("official_name", sa.String(length=255), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("subregion", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iso2"),
        sa.UniqueConstraint("iso3"),
        schema="trade_opportunity",
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=255), nullable=True),
        sa.Column("source_type", sa.String(length=100), nullable=True),
        sa.Column("base_url", sa.String(length=1000), nullable=True),
        sa.Column("update_frequency", sa.String(length=50), nullable=True),
        sa.Column("license_notes", sa.String(length=2000), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="trade_opportunity",
    )
    op.create_table(
        "hs_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
        schema="trade_opportunity",
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="trade_opportunity",
    )
    op.create_table(
        "hs_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hs_version_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hs_version_id"], ["trade_opportunity.hs_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["trade_opportunity.hs_codes.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trade_opportunity",
    )
    op.create_index(
        "ix_hs_codes_parent_id",
        "hs_codes",
        ["parent_id"],
        unique=False,
        schema="trade_opportunity",
    )
    op.create_index(
        "ix_hs_codes_version_code",
        "hs_codes",
        ["hs_version_id", "code"],
        unique=True,
        schema="trade_opportunity",
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("data_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_received", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_inserted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_updated", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_rejected", sa.Integer(), server_default="0", nullable=False),
        sa.Column("source_version", sa.String(length=100), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["trade_opportunity.data_sources.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trade_opportunity",
    )
    op.create_table(
        "product_aliases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["trade_opportunity.products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trade_opportunity",
    )
    op.create_table(
        "data_quality_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.Column("check_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("records_checked", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "failure_percentage", sa.Numeric(precision=8, scale=4), nullable=True
        ),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["trade_opportunity.ingestion_runs.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trade_opportunity",
    )
    op.create_table(
        "product_hs_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("hs_code_id", sa.Integer(), nullable=False),
        sa.Column("mapping_type", sa.String(length=50), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hs_code_id"], ["trade_opportunity.hs_codes.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["trade_opportunity.products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "hs_code_id", name="uq_product_hs_code"),
        schema="trade_opportunity",
    )
    op.create_table(
        "trade_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("reporter_country_id", sa.Integer(), nullable=False),
        sa.Column("partner_country_id", sa.Integer(), nullable=False),
        sa.Column("hs_code_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("period_type", sa.String(length=20), nullable=False),
        sa.Column("trade_flow", sa.String(length=20), nullable=False),
        sa.Column("trade_value", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("trade_value_currency", sa.String(length=3), nullable=True),
        sa.Column("trade_value_usd", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("quantity_unit", sa.String(length=50), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("source_record_id", sa.String(length=255), nullable=True),
        sa.Column("data_version", sa.String(length=100), nullable=True),
        sa.Column(
            "retrieved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hs_code_id"], ["trade_opportunity.hs_codes.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["partner_country_id"],
            ["trade_opportunity.countries.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_country_id"],
            ["trade_opportunity.countries.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["trade_opportunity.data_sources.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="trade_opportunity",
    )
    op.create_index(
        "ix_trade_data_hs_flow_period",
        "trade_data",
        ["hs_code_id", "trade_flow", "period_start"],
        unique=False,
        schema="trade_opportunity",
    )
    op.create_index(
        "ix_trade_data_partner_hs_period",
        "trade_data",
        ["partner_country_id", "hs_code_id", "period_start"],
        unique=False,
        schema="trade_opportunity",
    )
    op.create_index(
        "ix_trade_data_reporter_hs_period",
        "trade_data",
        ["reporter_country_id", "hs_code_id", "period_start"],
        unique=False,
        schema="trade_opportunity",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_trade_data_reporter_hs_period",
        table_name="trade_data",
        schema="trade_opportunity",
    )
    op.drop_index(
        "ix_trade_data_partner_hs_period",
        table_name="trade_data",
        schema="trade_opportunity",
    )
    op.drop_index(
        "ix_trade_data_hs_flow_period",
        table_name="trade_data",
        schema="trade_opportunity",
    )
    op.drop_table("trade_data", schema="trade_opportunity")
    op.drop_table("product_hs_codes", schema="trade_opportunity")
    op.drop_table("data_quality_results", schema="trade_opportunity")
    op.drop_table("product_aliases", schema="trade_opportunity")
    op.drop_table("ingestion_runs", schema="trade_opportunity")
    op.drop_index(
        "ix_hs_codes_version_code", table_name="hs_codes", schema="trade_opportunity"
    )
    op.drop_index(
        "ix_hs_codes_parent_id", table_name="hs_codes", schema="trade_opportunity"
    )
    op.drop_table("hs_codes", schema="trade_opportunity")
    op.drop_table("products", schema="trade_opportunity")
    op.drop_table("hs_versions", schema="trade_opportunity")
    op.drop_table("data_sources", schema="trade_opportunity")
    op.drop_table("countries", schema="trade_opportunity")
    # ### end Alembic commands ###
